#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Statusbar loop
while true; do
   xsetroot -name "$( date +"  %I:%M %p - %b %d, %Y  " )"
   sleep 30s    # Update time every minute
done &

[[ -f $HOME/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources &

# xrandr --output eDP1 --mode 1920x1200
# picom &
picom -b --unredir-if-possible --backend xr_glx_hybrid --vsync --use-damage --glx-no-stencil &
dunst &
# brillo -lS 20 &
~/.fehbg &
exec dwm
#DISPLAY=:0.0 exec dwm
