#!/bin/sh

# Enable Wayland Support for Firefox
export MOZ_ENABLE_WAYLAND=1

# Theming
export GTK_THEME=rose-pine-gtk
export QT_QPA_PLATFORMTHEME=qt5ct

# Other Options
export _JAVA_AWT_WM_NONREPARENTING=1
export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM=wayland
export XDG_SESSION_DESKTOP=river
export XDG_CURRENT_DESKTOP=river
#export XDG_CURRENT_DESKTOP=sway

# SSH Key Config
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
export SSH_ASKPASS=/usr/bin/ksshaskpass
export SSH_ASKPASS_REQUIRE=prefer

# Hardware Acceleration
export LIBVA_DRIVER_NAME=i965
export VDPAU_DRIVER=va_gl

nouveau-reclocking --max

#mako &
pcmanfm -d &
dbus-run-session river
