#!/usr/bin/env bash

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# *** Source Scripts ***
source ./theme.sh
source ./hotkeys.sh
source ./exec.sh
source ./rules.sh

# *** Misc. ***

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
